### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Megaf** [Megaf/707#1]
Initial revision of TODO, [WIP]

# FlightGear
- [ ] Separate aircraft type by its models, -020, -120, 220, 320, 320B, 320C, 420 and 700. Making them selectable in launcher. https://github.com/Megaf/707/issues/7
- [ ] Show only liveries that were available for the selected model. https://github.com/Megaf/707/issues/7
- [ ] Use correct engines for each model. https://github.com/Megaf/707/issues/7

# 3D
## Internal
- [ ] Make Auto Pilot area more realistic close to the real aeroplane.
## External
- [ ] Add more structural detail to wings flaps and slats.
- [ ] Add more detail to landing gears struts/suspension.

# Systems
## Auto Pilot
- [ ] Rewrite the whole thing.
## Hydraulic 
- [ ] Improve hydraulics.
- [ ] Remove LE Flaps Switch from the cockpit. Make LE Flaps work properly.

# FDM
## Aerodynamics
- [ ] Improve aerodynamics.
# Textures
- [ ] Add Varig Livery
- [ ] Add Aerolineas Argentinas Livery
- [ ] Add "Air Force One" Livery
