### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Megaf** [Megaf/707#15]
- [ ] Merge from WingAir https://github.com/Megaf/707/issues/10

- [ ] Merge from D-MKF1 https://github.com/Megaf/707/issues/9

- [ ] Remove pilots chat https://github.com/Megaf/707/issues/8

- [ ] Drop all variants, making only the 320C as close to real specs as possible. https://github.com/Megaf/707/issues/11

- [ ] Drop all liveries, make/update Boeings original livery. https://github.com/Megaf/707/issues/13

- [ ] Rewrite crash detection system. https://github.com/Megaf/707/issues/14

- [ ] Rewrite engine for the 320C, To spec. https://github.com/Megaf/707/issues/12

**Comment by puku-777** [comment]
seats are mine under #23

**Comment by puku-777** [comment]
claiming #22 as well

**Comment by Megaf** [comment]
Actually #22 is a bit more problematic, you sure?
